# Generated by Django 4.2.14 on 2024-08-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('rent_deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('car_class', models.CharField(max_length=50)),
                ('drive_unit', models.CharField(max_length=50)),
                ('fuel_type', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('engine_power', models.IntegerField()),
                ('transmission', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('car_number', models.CharField(max_length=50)),
                ('car_photo_url', models.URLField()),
                ('car_status', models.CharField(max_length=50)),
            ],
        ),
    ]
