# Generated by Django 4.2.14 on 2024-08-06 09:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodservice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='title')),
                ('category', models.CharField(max_length=128, verbose_name='category')),
                ('description', models.TextField(verbose_name='description')),
                ('product_amount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='product_amount')),
                ('image', models.ImageField(upload_to='product_photos', verbose_name='image')),
                ('price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='price')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'Product',
            },
        ),
        migrations.DeleteModel(
            name='Car',
        ),
    ]
